### ISSUE TITLE
Changed meaning of .+= in Julia 0.5

### ISSUE THREAD

**Issue by stevengj** [dfdx/NaiveBayes.jl#14]
Your code uses `x .+= y`, so you should know that in Julia 0.5 this has changed meaning to be equivalent to `broadcast!(identity, x, x .+ y)`, so that it mutates the `x` array (see JuliaLang/julia#17510 … in Julia 0.6 the whole operation will occur in-place without temporaries).  So `.+` should only be used if the left-hand side is a mutable array, and you don't mind mutating it.

At first glance, this looks like it is okay for you, because you use it in `m.x_counts[c] .+= X[:, j]`, where it looks like you want to work in-place anyway?  But if it were a problem you could always change it to `+=`.

**Comment by dfdx** [comment]
Thanks for reporting! Yes, in this case mutating lhs array is exactly what was intended, so changes in 0.5 and 0.6 will even make this code better, without any modifications :+1:
