### ISSUE TITLE
bug in fit method for Hybrid model

### ISSUE THREAD

**Issue by OmriTreidel** [dfdx/NaiveBayes.jl#15]
Discrete features currently need to be a subtype of `Int` which is Int64. This fails when the features are of positive integers type e.g `UInt8`. 

The fix should be to change `Int` to Integer

**Comment by JoshChristie** [comment]
I just noticed that `immutable HybridNB{C <: Integer, N}` for the labels doesn't seem right. Should labels be of type `Any`?

**Comment by dfdx** [comment]
From quick inspection of code I'd say it should be safe to generalize labels to be any type, so feel free to make a PR.

**Comment by OmriTreidel** [comment]
Changing it from Integer to a generic type is not entirely trivial since it needs to be written and read correctly to/from HDF5

**Comment by dfdx** [comment]
@OmriRoames as far as I can see from [User Guide](https://www.hdfgroup.org/HDF5/doc1.6/UG/11_Datatypes.html), HDF5 supports pretty wide range of types, including numbers, stings, arrays and compound types, so should we really worry about it?

**Comment by OmriTreidel** [comment]
Writing is not the main problem it easy to convert whatever types when writing, it's interpreting them correctly while reading. I'm not saying it's impossible, just takes a bit of work. I'll get onto it when I have a bit more time.
