### ISSUE TITLE
understanding nums.jl example

### ISSUE THREAD

**Issue by abieler** [dfdx/NaiveBayes.jl#20]
I just looked at the example nums.jl.

As far as I understand (please correct me if I am wrong):
3x5 matrix X denotes the observations. So 3 variables and 5 observations.

But after running the example:
m.n_obs = 11 (expected 5)
m.c_counts = :a => 4 (expected 3, because there are 3 :a in y), :b => 3 (expected 2)
I would also expect that `sum(m.c_counts) == m.n_obs` (I realize the sum does not work, but my intention is clear on what I mean, hopefully)

Can you please explain what I am missing?

Thanks
Andre

**Comment by dfdx** [comment]
Both of these discrepancies are result of Laplace smoothing: to make a model more robust and solve some computational issues, we "pretend" that we've observed each class and each feature once even before we start to actually count them. Here's an example of when it may be useful.

Imagine that you toss a coin 10 times and they result in all heads (H) and no tails (T). From pure frequentist perspective probability of getting H is 1 and probability of getting T is 0. But do you really believe you can never get T? I'd rather assume that probability of getting T is low, but not 0. 

Laplace smoothing boils down to adding a small number of "pseudo observations" to each possible class. In the example above we could add 1 to both - heads and tails - and get `P(H) = (10 + 1) / 12 = 11/12` and `P(T) = (0 + 1) / 12 = 1/12`, where 12 is a number of real observation + pseudo observations. 

In `MultinomialNB` amount of pseudo observations is controlled by `alpha` parameter in the constructor and has default value of 1. E.g. to remove smoothing altogether and get what you have expected use:

```
m = MultinomialNB(unique(y), 3; alpha=0)
```

However I'd suggest not to do it in practice: with large number of observations there's almost no difference between smoothed and "normal" models and with little observations smoothing may help to solve possible technical issues (e.g. division by zero when a feature or class haven't been encountered).

**Comment by abieler** [comment]
Thanks for taking time for this explanation!
You could just have told me to google laplace smoothing... ;)
