### ISSUE TITLE
Update package in Julia

### ISSUE THREAD

**Issue by joseespino** [dfdx/NaiveBayes.jl#3]
Could you update the package in Julia? Thanks

**Comment by dfdx** [comment]
Do you mean updating version of the package?

**Comment by dfdx** [comment]
Ok, I see it's failing. I'll fix it and release new version.

**Comment by dfdx** [comment]
Changes are in master, I'll tag new version in the evening.

**Comment by joseespino** [comment]
Ok, Thanks. Notify me when the update of the package is available in julia

**Comment by dfdx** [comment]
Version 0.2 is out, you can update. 

Closing this issue, feel free to reopen if I've missed something.

**Comment by joseespino** [comment]
Thanks
