### ISSUE TITLE
Release tag seems to reference non-existent revision

### ISSUE THREAD

**Issue by andyferris** [dfdx/NaiveBayes.jl#32]
I'm not sure if a force push went wrong somewhere, but v0.3.1 is supposed to reference revision `1e84bc5`. Every time I use Julia's package manager I get a warning about METADATA being ahead of my copy of the repository...

**Comment by dfdx** [comment]
On a clean clone of NaiveBayes.jl both:

    cat ~/.julia/v0.6/METADATA/NaiveBayes/versions/0.3.1/sha1

and 

    git rev-list -n 1 v0.3.1

give me the same hash: `1e84bc50771d741d19a9b8313ba060a6136e1576`.

Is it `rev-list` that produces a different output on your system? Can you completely reinstall NaiveBayes.jl and try again?

**Comment by andyferris** [comment]
OK, yes deleting it completely and re-adding it has made revision 1e86bc5 available. No matter how many `git fetch`s I did, my local repository didn't know about that revision at all, or the v0.3.1 tag.

Though it works, it's not in a great state as it appears eb1d671 has been force-pushed on top of 1e84bc5, so that the tag isn't associated with a branch anymore. I'm *guessing* that has something to do with why my local copy was confused, but it still seems to me that it should have been able to deal with it...

Thanks!

PS here's the top of the git commit tree that I see locally now:
```
* eb1d671 - (7 months ago) importing StatsBase.fit and .predict — Andrei Zhabinski (origin/master, cache/heads/master, master)
| * 1e84bc5 - (7 months ago) importing StatsBase.fit and .predict — Andrei Zhabinski (HEAD, tag: v0.3.1)
|/  
*   1ce0597 - (7 months ago) Merge pull request #26 from abieler/pull-request/ce576db7 — Andrei Zhabinski
|\  
| * ff41003 - (7 months ago) removes qualifiers for fit and predict calls — abieler (cache/pull/26/head)
| * ce576db - (7 months ago) fixes depwarns for v0.5 — abieler
|/  
...
```

**Comment by dfdx** [comment]
Hmm, normally I do force pushes only on branches with many little changes but could have made a mistake at some point. I believe tagging a new version should solve this issue for most users since they will never touch v0.3.1 at all. 

Given that Julia 0.6-rc is out and I'm slowly migrating my packages to it, I will try to kill two birds with one stone and tag a new version soon.

**Comment by andyferris** [comment]
Awesome - I agree it's not an issue that needs to be fixed, but I was confused why my local git copy couldn't cope. 

Thanks!

**Comment by dfdx** [comment]
Ok, I've created a `julia-v0.6` branch, but there are so many broken dependencies that I think I will wait a bit before investing more time into migrating NaiveBayes.jl.
