### ISSUE TITLE
Not compatible with `Float` arrays

### ISSUE THREAD

**Issue by abhijithch** [dfdx/NaiveBayes.jl#33]
I need to use `MultinomialNB` but on `Float64` arrays. Is it intentional that it only accepts `Int`?

**Comment by dfdx** [comment]
Multinomial distribution is discrete, hence `MultinomialNB` works only with discrete data. Perhaps, you are looking for `GaussianNB`?

**Comment by abhijithch** [comment]
I was trying to work on textual data and was trying to apply `MultinomialNB` on the tfidf. Maybe I simply use frequencies. Thanks.

**Comment by dfdx** [comment]
Although it's not mathematically sound, using multinomial NB for tf-idf makes sense to me. Feel free to make a PR to generalize the model to any type of number. I believe it should be as easy as replacing in [multinomial.jl](https://github.com/dfdx/NaiveBayes.jl/blob/master/src/multinomial.jl) all occurrences of `{Int64}` to `{T} .... where T <: Number`.
