### ISSUE TITLE
Compat woes

### ISSUE THREAD

**Issue by ablaom** [dfdx/NaiveBayes.jl#57]
@dfdx I've just given CompatHelper a kick, but it [now failing](https://github.com/dfdx/NaiveBayes.jl/runs/8197582918?check_suite_focus=true). Do you have any idea why? Have you perchance changed any of the following security keys?

```
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMPATHELPER_PRIV: ${{ secrets.COMPATHELPER_PRIV }}  # optional
```

Here is the current compat  status re this repo:

```julia
(jl_hXHOLu) pkg> status --outdated -m
Status `/private/var/folders/4n/gvbmlhdc8xj973001s6vdyw00000gq/T/jl_hXHOLu/Manifest.toml`
⌅ [34da2185] Compat v3.46.0 (<v4.2.0): HDF5
⌅ [f67ccb44] HDF5 v0.15.7 (<v0.16.11): NaiveBayes
⌅ [a98d9a8b] Interpolations v0.13.6 (<v0.14.4): NaiveBayes
```

**Comment by dfdx** [comment]
Hm, I don't remember changing any of these keys. In the repository settings I see that `COMPATHELPER_PRIV` was last updated updated 1.5 years ago. 

![image](https://user-images.githubusercontent.com/428171/188991260-c858d4d1-9bf7-49bc-b35a-05fa72ab2c07.png)

I don't observe `GITHUB_TOKEN` in the settings, but it seems like it's set automatically before every job. 

I also don't see significant differences between our [CompatHelper.yml](https://github.com/dfdx/NaiveBayes.jl/blob/master/.github/workflows/CompatHelper.yml) and the example in the docs.

**Comment by ablaom** [comment]
@dfdx Could you please update your COMPATHELPER_PRIV key? It looks like this is a access issue: 

https://github.com/dfdx/NaiveBayes.jl/actions/runs/2996703055/jobs/4807545087

**Comment by dfdx** [comment]
Ah, I was looking at the wrong example of the workflow itself :facepalm:  After copying its newest version, CompatHelper started to work. I'm going to run it, merge any PRs and tag a new version of NaiveBayes.jl.

**Comment by dfdx** [comment]
The [registration PR](JuliaRegistries/General/pull/68232) with all the updated versions is ready and should be merged soon.

**Comment by ablaom** [comment]
Thanks for that. Project.toml looks good now
