### ISSUE TITLE
Improve NB model creation

### ISSUE THREAD

**Issue by JoshChristie** [dfdx/NaiveBayes.jl#9]
Creating a model is rather annoying requiring us to specify the unique labels and the number of features. 

The current method of the package is to do the following:

``` julia
y = [1,2,2]
x = [1.0, 2.5, 3.2; 
        4.0  4.5  5.0]
model = GaussianNB(unique(y), size(x,1))
fit(model, x, label)
predict(m, xtest)
```

Could we instead pass in the desired naive bayes type into `fit()`. We could easily derive the unique labels and the number of features from the input data `x` and labels `y`. 

``` julia
model = fit(GaussianNB, x, y)
prediction = predict(model, xtest)

# so the function definitions would look something like
function fit(::Type{GaussianNB}, x::Vector{Vector{Any}}, label::Vector)
    # fit models to data and create the GaussianNB type
    GaussianNB(...)
end

function fit(::Type{MultinomialNB}, X, y)
     # fit models to data and create the GaussianNB type
     MultinomialNB(....)
end
```

We could then deprecate the existing usage. What are peoples thoughts on this?

**Comment by dfdx** [comment]
One of the design goals of this package is to support online learning. To do so, `MultinomialNB` and `GaussianNB` implement `fit` in such a way that it may be called multiple times on the same model but different batches. For obvious reasons, if we change it to `fit(::Type{SomeNB}, X, y)`, we will lose this possibility. 

In general, I see a particular split between machine learning and statistics communities in Julia. Stats guys tend to use signature you proposed, i.e. `fit(::Type{Model}, ...)`, but ML guys seem to prefer `fit(::Model, ...)` (note that the name "fit" may be changed to "train" or "learn", see discussion at JuliaML/Roadmap.jl#8). 

Note, that in theory it's still possible to automatically determine the number of labels by dynamically adding them, but this requires some experimenting that I don't really have time for at the moment. PR is welcome, though.

**Comment by OmriTreidel** [comment]
I think there is another drawback: One may want to have a NB model with various parametric and non-parametric distributions, so the model should really be defined with a list/tuple of the distribution of each feature. Maybe a list of pairs `(name, distribution)`.

**Comment by JoshChristie** [comment]
Sounds good. Happy to keep it the way it is. Thanks for the link too. 
Will work on PR to determine the number of labels soon (hopefully).
